### ISSUE TITLE
Support For Cocoapods

### ISSUE THREAD

**Issue by pacu** [apple/swift-crypto#102]
#### Motivation:
Even though Swift Package Manager is gaining traction. Cocoapods will still be around for a while and it's widely used in the iOS and MacOS ecosystem. 

#### Importance:
This allows existing applications to use this library instead of falling back to older, less updated and maintained libraries.

**Comment by Lukasa** [comment]
On iOS and macOS this library essentially entirely stops existing: it just re-exports CryptoKit. Is there something you're looking to gain that isn't that?

**Comment by pacu** [comment]
Oh! I see, thank you so much! I wasn't aware of that. I apologize for the dumb question.
