### ISSUE TITLE
Swift Crypto to validate iOS app receipts

### ISSUE THREAD

**Issue by carlosdelamora** [apple/swift-crypto#18]
I would like to know if is possible to use swift-crypto to validate iOS app receipts with out the need to use other non-native libraries like OpenSSL. If this is possible I would appreciate if someone can point me to the appropriate documentation on how to do this.

**Comment by Lukasa** [comment]
I'm afraid it is not. In particular there are requirements on X.509 that are not addressed by Swift Crypto.
