### ISSUE TITLE
[Github] Add topics to make repo more easy to find

### ISSUE THREAD

**Issue by Sajjon** [apple/swift-crypto#20]
### Issue template is not applicable, this relates to Github.

We should add topics to the repo to make it more easy to find, e.g:
* `cryptography`
* `crypto`
* `elliptic-curves`
* `ECDSA`
* `EdDSA`
* `ECDH`
* `Diffie-Hellman`
* `hash-functions`

Possibly also some of the hash functions by name?
* `sha256`
* `sha384`

Possible also some of the curves?
* `Curve25519`
* `P256`
* `P521`
* `secp256r1`      (<-- SECG naming of `P-256`)
* `prime256v1 `  (<--  ANSI X9.62 naming of `P-256`)

**Comment by Lukasa** [comment]
/cc @tomerd 

Tom, I think it's probably worth putting `cryptography`, `elliptic-curves`, `hash-functions`, `ciphers`, `ECDSA`, `ECDH`, and `EdDSA` into the topics for this repo.

**Comment by Sajjon** [comment]
Ping @tomerd :)

**Comment by tomerd** [comment]
✅
