### ISSUE TITLE
Add Sendable annotation to Crypto Extras

### ISSUE THREAD

**Issue by 0xTim** [apple/swift-crypto#208]
#### Motivation:

Use Swift Crypto types in concurrency contexts invariably starts to hit issues as no types are Sendable. I'm aware there are issues around the main Crypto target as that has match CryptoKit (or does it? Could we add Sendable conformance on Linux?) but it would be great to add it to the types in Crypto Extras

#### Importance:

It's possible to achieve this with a mix of `@preconcurrency` and `@unchecked Sendable` but neither of these are ideal for obvious reasons.

**Comment by Lukasa** [comment]
Yes, the goal is that the Crypto API exactly matches the CryptoKit one. This avoids users needing to deal with platform-specific imports or other logic.

For CryptoExtras, this can definitely be done separately. @rnro want to take a look at CryptoExtras?

**Comment by rnro** [comment]
Yep, sure.

**Comment by 0xTim** [comment]
Fixed in #211
