### ISSUE TITLE
How to set CBC padding behavior?

### ISSUE THREAD

**Issue by lovetodream** [apple/swift-crypto#209]
### Question Checklist

- [x] I'm using the latest version of Swift Crypto (master branch)
- [x] I read the [Contribution Guidelines](https://github.com/apple/swift-crypto/blob/master/CONTRIBUTING.md)
- [x] I searched for [existing GitHub issues](https://github.com/apple/swift-crypto/issues)

### Question Subject
I'm currently using CryptoSwift for CBC de-/encryption and I'd like to move that to swift-crypto.
For my use-case I have to disable automatic padding, is that possible?

#### Question Description
Currently I have the following code to decrypt a CBC encrypted payload sent from an Oracle db server during authenticating:
```swift
func decryptCBC(_ key: [UInt8], _ encryptedText: [UInt8]) throws -> [UInt8] {
    let iv = [UInt8](repeating: 0, count: 16)
    let aes = try AES(key: key, blockMode: CBC(iv: iv), padding: .noPadding)
    return try aes.decrypt(encryptedText)
}
```

I tried migrating it to swift-crypto and now it does automatic padding and fails with `CryptoKitError.incorrectParameterSize`, when trying to trim the padding:
```swift
func decryptCBC(_ key: [UInt8], _ encryptedText: [UInt8]) throws -> Data {
    let iv = [UInt8](repeating: 0, count: 16)
    return try AES._CBC.decrypt(encryptedText, using: .init(data: key), iv: AES._CBC.IV(ivBytes: iv)) // noPadding equivalent?
}
```

I guess I'll have the same problem on encryption.
```swift
// current (CryptoSwift):
func encryptCBC(_ key: [UInt8], _ plainText: [UInt8], zeros: Bool = false) throws -> [UInt8] {
    var plainText = plainText
    let blockSize = 16
    let iv = [UInt8](repeating: 0, count: blockSize)
    let n = blockSize - plainText.count % blockSize
    if n != 0, !zeros {
        plainText += Array<UInt8>(repeating: UInt8(n), count: n)
    }
    let aes = try AES(key: key, blockMode: CBC(iv: iv), padding: zeros ? .zeroPadding : .noPadding)
    var encryptor = try aes.makeEncryptor()
    return try encryptor.update(withBytes: plainText, isLast: true) + encryptor.finish()
}

// new (swift-crypto):
func encryptCBC(_ key: [UInt8], _ plainText: [UInt8], zeros: Bool = false) throws -> Data {
    var plainText = plainText
    let blockSize = 16
    let iv = [UInt8](repeating: 0, count: blockSize)
    let n = blockSize - plainText.count % blockSize
    if n != 0, !zeros {
        plainText += Array<UInt8>(repeating: UInt8(n), count: n)
    }
    return try AES._CBC.encrypt(plainText, using: .init(data: key), iv: AES._CBC.IV(ivBytes: iv)) // set padding behavior?
}
```

This is the related code: https://github.com/lovetodream/oracle-nio/blob/main/Sources/OracleNIO/Helper/Crypto.swift

**Comment by Lukasa** [comment]
So we can add an overload here that avoids the padding. It should be pretty easy really, it's much like the identical code with a check that the length is exactly a multiple of the block size and then skipping appending the final padding block. The existing implementation and the new one can funnel into the same shared code.

Would you be open to writing that patch?

**Comment by lovetodream** [comment]
Yeah, sure

**Comment by lovetodream** [comment]
Do you know of any test files I could include for testing the version without padding @Lukasa?

**Comment by Lukasa** [comment]
There isn't any good source for this: unpadded CBC is pretty rare. You may be able to find some in some RFCs.
