### ISSUE TITLE
New API Proposal: Add `SHA1` hash function 

### ISSUE THREAD

**Issue by Mordil** [apple/swift-crypto#23]
### New API Proposal: Add `SHA1` hash function 

Motivation:

It is common to use SHA1 hashes to uniquely identify a collection of files (or data) for a quick lookup reference.

[Redis](https://redis.io/commands/evalsha) uses this for caching Lua scripts that have been executed to improve JIT performance and for faster execution (if supported by the Redis client).

In SwiftNIO, a comment was written describing a future where the Swift Standard Library or Foundation would provide the SHA1 hash, so they wouldn't maintain their own for [Web Sockets](https://github.com/apple/swift-nio/blob/master/Sources/NIOWebSocket/SHA1.swift#L30).

Importance:

In [RediStack](https://gitlab.com/mordil/swift-redi-stack) we will be using a SHA1 implementation to provide client-side optimistic caching of Redis Lua scripts, as many other clients do.

As we cannot rely on [SwiftNIO's](https://github.com/apple/swift-nio/blob/master/Sources/NIOWebSocket/SHA1.swift#L17) implementation, as it is internal, and their OpenSSL C wrapper API is not considered stable, we've pulled in [CryptoSwift's](https://gitlab.com/Mordil/swift-redi-stack/-/blob/d384deb011584f3753068cbe51cb1a55562f5ad7/Sources/RediStack/SHA1.swift#L15) implementation.

Given the regular use case for SHA1 hashing, having Crypto provide a "common currency" type just like the SHA256, 384, and 512.

**Comment by Lukasa** [comment]
SHA1 is present as `Insecure.SHA1`

**Comment by Sajjon** [comment]
I love that's marked `Insecure` using that namespace, great for highlighting "do not use this".
