### ISSUE TITLE
API Change Proposal: Add details in errors

### ISSUE THREAD

**Issue by Sajjon** [apple/swift-crypto#25]
#### Motivation:

One of the many strengths of Swift is to be able to pass values to enum cases, often used to model Errors. 

```swift
public enum CryptoKitError: Error {
    case incorrectKeySize
    case incorrectParameterSize
    case authenticationFailure
    case underlyingCoreCryptoError(error: Int32)
}
```

When I see a error of type `CryptoKitError`, e.g. case `incorrectKeySize` I don't get any info about which key size was expected and which was used.

I propose that we add some details, e.g. like so:

```swift
public enum CryptoKitError: Error {
    case incorrectKeySize(expectedSize: UInt32, butGot: UInt32)
    case incorrectParameterSize(expectedSize: UInt32, butGot: UInt32)
    case authenticationFailure
    case underlyingCoreCryptoError(error: Int32)
}
```

This will of course require change of [CryptoKit.CryptoKitError](https://developer.apple.com/documentation/cryptokit/cryptokiterror), making this change non-trivial. 

#### Importance:
It's a really small addition, but greatly benefits users. Depending on the formatting of `localizedDescription`/`description`/`debugDescription` we can display a much more rich message, giving clear context to the user:

```swift
"Error: incorrect size of key, expected key size of 256 bits, but you passed a key of length 521 bits"
``` 
(Or what similar) makes it much more clear what went wrong and how I ought to debug the error.

**Comment by Lukasa** [comment]
Unfortunately, doing this is extremely difficult: it breaks the ABI of CryptoKit and the API of Swift Crypto. Enums are fundamentally difficult to extend. I don't think the idea is wrong, but sadly this genie cannot be put back into the bottle very easily, so I think we need to live with the status quo for now.

**Comment by jshier** [comment]
@Lukasa Would it be possible to add details to the *new* errors for 1.1? It would be great if the new `invalidPrivateKey` case could have some associated values, or if the new `CryptoKitASN1Error` type could have some associated values.
