### ISSUE TITLE
Include C++ implementations of BoringSSL algorithms

### ISSUE THREAD

**Issue by fpseverino** [apple/swift-crypto#300]
In BoringSSL some algorithms, like ML-KEM and ML-DSA, are written in C++, but the [`vendor-boringssl.sh` script](https://github.com/apple/swift-crypto/blob/main/scripts/vendor-boringssl.sh) doesn't look for `.cc` files inside BoringSSL’s `crypto` directory.

### New Issue Checklist

- [X] I'm using the latest version of Swift Crypto (`main` branch)
- [X] I read the [Contribution Guidelines](https://github.com/apple/swift-crypto/blob/main/CONTRIBUTING.md)
- [X] I searched for [existing GitHub issues](https://github.com/apple/swift-crypto/issues)

### Expected behavior

Being able to use methods from algorithms written in C++

### Actual behavior

Not being able to use methods from algorithms written in C++

### Steps to reproduce

1. Add the header file of an algorithm written in C++ inside `Sources/CCryptoBoringSSL/include/CCryptoBoringSSL.h`
2. Import `CCryptoBoringSSL`
3. Try to use a `CCryptoBoringSSL_xxx` method of an algorithm written in C++

### Swift Crypto version/commit hash

commit: ff0f781cf7c6a22d52957e50b104f5768b50c779

### Environment

<details>
  <pre>Swift version: Apple Swift version 6.0.2 (swiftlang-6.0.2.1.2 clang-1600.0.26.4)
Target: arm64-apple-macosx15.0
Unix version: Darwin MacBookPro.wind3.hub 24.1.0 Darwin Kernel Version 24.1.0: Thu Oct 10 21:05:14 PDT 2024
 root:xnu-11215.41.3~2/RELEASE_ARM64_T8103 arm64

macOS version: 15.1.1
Xcode-select path: '/Applications/Xcode.app/Contents/Developer
Xcode: Xcode 16.1 (Build version 16B40)
</pre>
</details>

**Comment by Lukasa** [comment]
Thanks for filing this @fpseverino! Let's nail this down before we move forward on #278 and #267, as I'd like us to make sure we aren't going to regress those.

**Comment by fpseverino** [comment]
I agree @Lukasa! This will need a BoringSSL update too, right? It's something that I can/should do?

**Comment by Lukasa** [comment]
It's going to be a lot easier for me to do it than you, I suspect

**Comment by fpseverino** [comment]
All right, just to clarify, would you also take care of updating the script or would you prefer me to do it?

**Comment by Lukasa** [comment]
I can update the script as well. :smile:

**Comment by Lukasa** [comment]
Huh, turns out that we timed this work well, as that immediately became  100% necessary! https://boringssl.googlesource.com/boringssl/+/5813c2c10c73d800f1b0d890a7d74ff973abbffc
