### ISSUE TITLE
could not build Objective-C module 'Crypto'

### ISSUE THREAD

**Issue by davegomez** [apple/swift-crypto#45]
### Question Checklist

- [x] I'm using the latest version of Swift Crypto (master branch)
- [x] I read the [Contribution Guidelines](https://github.com/apple/swift-crypto/blob/master/CONTRIBUTING.md)
- [x] I searched for [existing GitHub issues](https://github.com/apple/swift-crypto/issues)

### Question Subject

I'm having a hard time trying to use the library in a new multiplatform Swift library that I'm trying to create.

The project doesn't build.

#### Question Description

Whenever I try to build the project I get the following errors:

```bash
warning: dependency 'swift-crypto' is not used by any target
<path>/.build/x86_64-apple-macosx/debug/Crypto.build/module.modulemap:2:12: error: header '<path>/.build/x86_64-apple-macosx/debug/Crypto.build/Crypto-Swift.h' not found
    header "<path>/.build/x86_64-apple-macosx/debug/Crypto.build/Crypto-Swift.h"
           ^
<path>/<file>.swift:2:8: error: could not build Objective-C module 'Crypto'
import Crypto
       ^
<path>/.build/x86_64-apple-macosx/debug/Crypto.build/module.modulemap:2:12: error: header '<path>/.build/x86_64-apple-macosx/debug/Crypto.build/Crypto-Swift.h' not found
    header "<path>/.build/x86_64-apple-macosx/debug/Crypto.build/Crypto-Swift.h"
           ^
<path>/<file>.swift:2:8: error: could not build Objective-C module 'Crypto'
import Crypto
```

```
Apple Swift version 5.2.4 (swiftlang-1103.0.32.9 clang-1103.0.32.53)
Target: x86_64-apple-darwin19.5.0
```

I already try using different versions of the library including the `1.1.0-rc.1` and `master` but I'm getting the same issue.

In some related questions, I can't find information about how to use it with binary data without importing **Foundation** to access de **Data** class.

Is it possible to work with binary data in a multiplatform library using swift-crypto (without Foundation)?

**Comment by Lukasa** [comment]
How are you attempting to build Crypto?

And no, it is not possible to use swift-crypto without Foundation.

**Comment by davegomez** [comment]
Hey @Lukasa, thank you for the quick response 🙂.

This is the first time I'm working with Crypto or CryptoKit so I want to get to know the library and how to use it. My idea so far is just to get a hash using `SHA256` but I can't even get to the second line of the file because the project doesn't build due the error I posted above.

I already tried to build the project importing Foundation before and after but no change at all.

I'm also pretty new at this cross-platform Swift so I wonder. 

How it is possible for swift-crypto to work on Linux if it needs Foundation?

Is it possible to import Foundation in Linux?

**Comment by 0xTim** [comment]
@davegomez Foundation is available on Linux (and all platforms that Swift supports)

**Comment by 0xTim** [comment]
@davegomez Are you adding Crypto as a dependency to the target as well as the manifests dependencies?

**Comment by davegomez** [comment]
I'm not @0xTim, I blame my NodeJS background for that.

I'm going to check those other places to see if this might be the problem.

Thanks!

**Comment by davegomez** [comment]
Adding it to the dependencies in the `target` solved it.

Thank you, folks.

**Comment by Lukasa** [comment]
Thanks for helping out @0xTim, and I'm glad your problem was resolved @davegomez!
