### ISSUE TITLE
SPM CryptoSwift 

### ISSUE THREAD

**Issue by igor-fn37** [apple/swift-crypto#48]
### New Issue Checklist

- [x] I'm using the latest version of Swift Crypto (master branch)
- [x] I read the [Contribution Guidelines](https://github.com/apple/swift-crypto/blob/master/CONTRIBUTING.md)
- [x] I searched for [existing GitHub issues](https://github.com/apple/swift-crypto/issues)

### Expected behavior
Use SwiftOTP via SPM without errors.

### Actual behavior
Error while compiling the project: 

```
The package product 'CryptoSwift' requires minimum platform version 9.0 for the iOS platform, but this target supports 8.0 (in target 'SwiftOTP' from project 'SwiftOTP')
```

### Steps to reproduce

1. Create the empty Xcode project.
2. Add SwiftOTP package dependency.
3. Compile the project.
4. Get compile error.

**Comment by 0xTim** [comment]
@igor-fn37 judging by the error you're trying to build SwiftOTP with [this manifest](https://github.com/lachlanbell/SwiftOTP/blob/master/Package.swift#L10). That refers to [CryptoSwift](https://github.com/krzyzanowskim/CryptoSwift) which is a different package to this one (Swift Crypto)

(As an aside, to fix the error you need to set your minimum iOS platform version to 9.0 as the message says)

**Comment by Lukasa** [comment]
Yes, this is not `CryptoSwift`.
