### ISSUE TITLE
A build warning is viewed on Linux in Swift 5.3.

### ISSUE THREAD

**Issue by YOCKOW** [apple/swift-crypto#51]
### New Issue Checklist

- [x] I'm using the latest version of Swift Crypto (master branch)
- [x] I read the [Contribution Guidelines](https://github.com/apple/swift-crypto/blob/master/CONTRIBUTING.md)
- [x] I searched for [existing GitHub issues](https://github.com/apple/swift-crypto/issues)

### Expected behavior
No warnings are viewed while building.

### Actual behavior

A warning like below is viewed.

```console
/code/Sources/Crypto/Util/SecureBytes.swift:265:13: warning: using '_' to ignore the result of a Void-returning function is redundant
            _ = self.withUnsafeMutablePointerToElements { elementsPtr in
            ^~~~
```

### Steps to reproduce

Exec `swift build` on Linux in Swift 5.3.

### Swift Crypto version/commit hash

Ver. 1.1.1

### Reason

`memset_s` returns `errno_t` on Darwin.
On the other hand, `memset_s` that [is implemented in this library](https://github.com/apple/swift-crypto/blob/1.1.1/Sources/Crypto/Util/BoringSSL/Zeroization_boring.swift) returns `Void`.

### Environment

```console
Swift version 5.3 (swift-5.3-RELEASE)
Target: x86_64-unknown-linux-gnu

OS: Ubuntu 18.04
Linux df91427aa21c 4.19.76-linuxkit #1 SMP Tue May 26 11:42:35 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by Lukasa** [comment]
Great catch! It should be sufficient just to fix up the `memset_s` implemented in this module. Are you happy to make that patch?

**Comment by YOCKOW** [comment]
@Lukasa 
Of course. I'm going to try.
Thank you for the response.
