### ISSUE TITLE
Add SwiftWasm support / remove need for BoringSSL networking methods

### ISSUE THREAD

**Issue by Sajjon** [apple/swift-crypto#58]
#### Motivation:

Hey! I try to compile `swift-crypto` with [SwiftWasm](https://book.swiftwasm.org/index.html), using command:

```bash
swift build --triple wasm32-unknown-wasi
```

Which produces the following compilation error:

```bash
~/Developer/Swift/swift-crypto/Sources/CCryptoBoringSSL/crypto/bio/socket_helper.c:28:10: fatal error: 'netdb.h' file not found
#include <netdb.h>
         ^~~~~~~~~
.
[358/406] Compiling curve25519.c
```
Which is caused by the fact that [networking is not standardized/supported by WebAssembly (issue from April 2019)](https://github.com/WebAssembly/wasi-libc/issues/18).

However, this networking part of BoringSSL does not really seem needed for me to be able to **offline** be performing crypto primitives!

So feels like we should be able to skip these parts of BoringSSL?

I propose that we change the wrapper around BoringSSL so that we can use just what we need in BoringSSL so that hopefully `swift-crypto` can work with SwiftWasm.

#### Importance:

[WebAssembly is on the rise (Google Trends)](https://trends.google.com/trends/explore?date=today%205-y&q=wasm) and SwiftWasm seems to be the primary project bringing Wasm support to Swift. If it is possible to make swift-crypto work with SwiftWasm with a small amount of work I think it would be very beneficial to the Swift and WebAssembly community.

**Comment by AndrewBarba** [comment]
I have an initial implementation here: https://github.com/apple/swift-crypto/pull/145

I've verified that this complies and runs on WASM applications.

**Comment by AndrewBarba** [comment]
Merged https://github.com/apple/swift-crypto/pull/145 💯
