### ISSUE TITLE
This repo should have the official snapshot tags or the toolchain should check out a pre-existing tag

### ISSUE THREAD

**Issue by buttaface** [apple/swift-crypto#73]
Now that this repo is part of the official toolchain as a dependency of SPM, it should have [regular snapshot tags like swift-driver](https://bugs.swift.org/projects/SR/issues/SR-13771) and other SPM dependencies.

cc @yim-lee @shahmishal

**Comment by buttaface** [comment]
Alternately, if SPM doesn't really need to build against the main branch of this repo, you could just checkout a particular pre-existing tag of this repo instead, [like `swift-argument-parser` does](https://github.com/apple/swift/blob/2766cad22c0f86d6c00757d7ccff82a5d3322d85/utils/update_checkout/update-checkout-config.json#L68).

**Comment by yim-lee** [comment]
> SPM doesn't really need to build against the main branch of this repo, you could just checkout a particular pre-existing tag of this repo instead, like swift-argument-parser does.

That's the plan. We use `main` to test out the changes and fixes that we need first. Now that things have stabilized I think we can ask @Lukasa to cut a release and have SwiftPM pin to it.

**Comment by buttaface** [comment]
Great, I just tested cross-compiling SPM for Android from the Feb. 9 trunk source snapshot that builds this repo too, and had no problem building it (haven't tried running the SPM tests for that tag yet). I have [a pull forthcoming to SPM with that](https://github.com/buttaface/termux-packages/blob/swift54/packages/swift/swiftpm-Utilities-bootstrap), so thought it'd be good to get the tagging scheme for this repo worked out too.

**Comment by Lukasa** [comment]
Tagged 1.1.4.

**Comment by yim-lee** [comment]
Thanks @Lukasa.

@buttaface Here are the related PRs:
- https://github.com/apple/swift-package-manager/pull/3282
- https://github.com/apple/swift/pull/35999
