### ISSUE TITLE
New API Proposal: Add (expose) ECC methods

### ISSUE THREAD

**Issue by Sajjon** [apple/swift-crypto#9]
### Motiviation

We should expose some Elliptic Curve Cryptography (ECC) methods, at least:
1.  Point multiplication
2. Decode `point on curve` from a compressed public key.

So that developers can develop cryptographic constructs using these fundamental building blocks. e.g. [ECIES](https://en.wikipedia.org/wiki/Integrated_Encryption_Scheme) (here is [my implementation](https://github.com/radixdlt/radixdlt-swift/blob/develop/Sources/Stack/1_Subatomic/Crypto/Encryption/ECIES.swift))

An (EC) crypto lib which does not expose at least these above-mentioned methods is extremely limiting.

#### Alternate solution
Alternatively, we can include common cryptographic constructs such as above mentioned _ECIES_ in this library - but it is more limiting and sounds like lots of work - and more maintenance....

### Importance
If above mentioned cryptographic primitives - especially EC point multiplication - are not expose then crypto companies and cryptocurrency project might have to turn to other solutions. Which would be sad really, since this repo could improve the whole crypto sphere (on the Swift side of things).

**Comment by Lukasa** [comment]
Thanks for this proposal!

I think at this time this proposal is explicitly out of scope. The goal of this library is to provide safe, high-level constructions; we are not trying to expose primitives for composition. I appreciate that this is limiting, but we want to avoid the kitchen-sink style API design of lower-level libraries. 

I think there is absolutely value in high-quality libraries exposing primitives for Swift users interested in implementing novel or unusual cryptographic constructions, but that belongs elsewhere. 

Thanks for the proposal though, please keep them coming!

**Comment by FredericJacobs** [comment]
Hey @Sajjon,

Thanks for the proposal!

I just want to point out that in order to perform ECIES, everything is already there. 
The only operation you need to perform over elliptic curves is a DH key agreement which we expose on the EC private key types.

See this example for P256: https://developer.apple.com/documentation/cryptokit/p256/keyagreement/privatekey/3243096-sharedsecretfromkeyagreement

**Comment by Sajjon** [comment]
@FredericJacobs @Lukasa Thanks for pointing that out Frederic! So how do you feel about including an implementation of `ECIES` - if I were to do a (draft) PR with an initial implementation?

**Comment by FredericJacobs** [comment]
Primitives used in ECIES will vary from protocol to protocol. We are currently not taking any PRs for higher-level constructions that can be built on top of Swift Crypto. If you are interested, we have an ECIES variant [in the Swift playground that was released at WWDC](https://developer.apple.com/documentation/cryptokit/performing_common_cryptographic_operations).

**Comment by Sajjon** [comment]
@FredericJacobs Got it, makes sense.

Thanks for that playground, I have not seen it before. Now that I've looked at it, it contains some typos, multiple instances of:
_"ephmeral"_ -> _"ephemeral"_

Very nice playground! I must start using playgrounds more, it's kind of similar to Juniper "books" in Python.
