### ISSUE TITLE
Type 'P256.Signing.ECDSASignature' has no member 'composite'

### ISSUE THREAD

**Issue by pahnev** [apple/swift-crypto#99]
### Question Checklist

- [x] I'm using the latest version of Swift Crypto (master branch)
- [x] I read the [Contribution Guidelines](https://github.com/apple/swift-crypto/blob/master/CONTRIBUTING.md)
- [x] I searched for [existing GitHub issues](https://github.com/apple/swift-crypto/issues)

### Question Subject
Type 'P256.Signing.ECDSASignature' has no member 'composite'

![Screenshot 2021-12-14 at 12 30 09](https://user-images.githubusercontent.com/2078494/145982644-870a5972-55b3-421e-af30-5b039daad257.png)

#### Question Description
As Xcode is able to find the variable, we know it's there. Looking at the [source code](https://github.com/apple/swift-crypto/blob/22fd38919566816705c57d5f4dd5a97a4edcf25e/Sources/Crypto/Signatures/ECDSA.swift#L62) it seems to have internal access control. Is that by design or could it be made public?

**Comment by Lukasa** [comment]
This is by design: the `composite` accessor is not available in CryptoKit. You can effectively reconstitute it by slicing `rawRepresentation` in half.
